### ISSUE TITLE
the MITETracker.py can NOT make directory results/jobname

### ISSUE THREAD

**Issue by XuewenWangUGA** [INTABiotechMJ/MITE-Tracker#1]
The run error. The MITETracker.py can NOT make subdirectory , here is the "results/xgenome".

my run command: ( in linux)
python3 /usr/local/apps/gb/MITE-Tracker/0.1/MITETracker.py -g $srcdir/$seqf -w $threads -j xgenome

It may be caused by where is the parent dir . Does this script call the current directory or use the directory information from input seq file? It seems the parent dir info passing is wrong.

Error information:
Traceback (most recent call last):
  File "/usr/local/apps/gb/MITE-Tracker/0.1/MITETracker.py", line 55, in <module>
    os.mkdir("results/" + args.jobname)
FileNotFoundError: [Errno 2] No such file or directory: 'results/xgenome'

**Comment by juancresc** [comment]
The results directory should be in the same hd as the program itself. The expected command for running is:

`python3 -m MITETracker -g $srcdir/$seqf -w $threads -j xgenome
`

**Comment by EricDeveaud** [comment]
result dir may be out of install dir. 
following patch wil generate results directory on pwd
```
--- MITETracker.py.ori
+++ MITETracker.py
@@ -53,7 +53,7 @@ file_names['file_candidates_dir'] = "results/" + args.jobname + "/temp/"

 #write dir for results
 if not os.path.isdir("results/" + args.jobname):
-    os.mkdir("results/" + args.jobname)
+    os.makedirs("results/" + args.jobname)

 if not os.path.isdir("results/" + args.jobname + "/tmp"):
     os.mkdir("results/" + args.jobname + "/tmp")
@@ -63,7 +63,7 @@ if os.path.isdir(file_names['file_temp_cluster_dir']):
 os.mkdir(file_names['file_temp_cluster_dir'])


-filename = os.path.join(os.path.dirname(os.path.realpath(__file__)), "results/" + args.jobname + "/out.log")
+filename = os.path.join("results/" + args.jobname + "/out.log")
 logging.basicConfig(filename=filename,level=logging.DEBUG,format='%(asctime)s %(message)s')

 MITE_MAX_LEN = args.mite_max_len
```

Eric
