### ISSUE TITLE
Results not complete

### ISSUE THREAD

**Issue by amdelaa** [INTABiotechMJ/MITE-Tracker#13]
Hello..
I and my friends are trying to use MITE Tracker to find MITEs in Solanum lycopersicum. I would like to ask 2 questions:

1. After several hours waited, We were so glad that the running was successful. In README file, it is said that there are 4 results in the "results" folder: 3 files in .fasta format, and 1 file in  .gff3 format. Unfortunately, the result showed only MITE candidates in .fasta and .csv. 

What should we do to get all the four files in the results?

2. In .csv file, there is a column entitled "tsd_in" with "yes" or "no" description in every mite candidate lines. What is "tsd_in" means? 

Thank you..

**Comment by juancresc** [comment]
I wouldnt pay much attention to that but it's just a description of whether the TSD was found inside the TIR or outside.

**Comment by juancresc** [comment]
Related to one, can you share the terminal output of the program?

**Comment by Max-hub1** [comment]
> Hello.. I and my friends are trying to use MITE Tracker to find MITEs in Solanum lycopersicum. I would like to ask 2 questions:
> 
> 1. After several hours waited, We were so glad that the running was successful. In README file, it is said that there are 4 results in the "results" folder: 3 files in .fasta format, and 1 file in  .gff3 format. Unfortunately, the result showed only MITE candidates in .fasta and .csv.
> 
> What should we do to get all the four files in the results?
> 
> 2. In .csv file, there is a column entitled "tsd_in" with "yes" or "no" description in every mite candidate lines. What is "tsd_in" means?
> 
> Thank you..

I have also encountered the first problem. It seems that the clustering process stopped abnormally. Could you tell me how to solve it?  The log is as follows.
[out.log](https://github.com/INTABiotechMJ/MITE-Tracker/files/11683605/out.log)

**Comment by juancresc** [comment]
Do you want to share the genome so we can try to run it? I don't see any errors in the logs which is weird.

**Comment by Max-hub1** [comment]
Thank you for your reply. 
I am a newbie to the field of bioinformatics. I am trying to use MITE Tracker to find MITEs in Arabidopsis Thaliana, which you have already done in your paper. In tools_comparison.csv file, it is said there are 38 families. Unfortunately, I can’t get this result and I can only get initial clusters as the log shows. Here is my command line and genome file.

command line: 
nohup python3.8 -m MITETracker -g ./tasks/Arabidopsis_Thaliana.fna -w 10 -j ata_6.9 &

genome file: it's too big to upload. 

Here is the website where I download the file from:
https://www.ncbi.nlm.nih.gov/genome/?term=Arabidopsis%20Thaliana

**Comment by juancresc** [comment]
what's the RAM memory in the machine you're using?

**Comment by Max-hub1** [comment]
![ram](https://github.com/INTABiotechMJ/MITE-Tracker/assets/73773051/2c818a50-5807-4be0-ba22-7a46c6ea02a5)

**Comment by Max-hub1** [comment]
I ran this program many times these days. The results were the same. 
[out.log](https://github.com/INTABiotechMJ/MITE-Tracker/files/11735711/out.log)
![result](https://github.com/INTABiotechMJ/MITE-Tracker/assets/73773051/dd08f9bd-147b-438f-ab60-2fe7468d0250)

**Comment by juancresc** [comment]
@Max-hub1 
i was able to run AT genome, here are the logs and results
[res.zip](https://github.com/INTABiotechMJ/MITE-Tracker/files/11736683/res.zip)


```
pip freeze           
WARNING: Could not generate requirement for distribution -umpy 1.22.3 (/home/juan/Documents/dev/bio/MITE-Tracker/venv/lib/python3.8/site-packages): Invalid requirement, parse error at "'-umpy==1'"
biopython==1.79
Cython==0.29.28
numpy==1.22.3
pandas==1.4.2
python-dateutil==2.8.2
pytz==2022.1
six==1.16.0

```

**Comment by Max-hub1** [comment]
Following your reply, I updated the version of the python package and ran the program again. The program runs successfully. Many thanks.
