### ISSUE TITLE
TIRs longer than Mites

### ISSUE THREAD

**Issue by madelhorius** [INTABiotechMJ/MITE-Tracker#4]
Hi,
I used your software to detect MITEs in a plant genome assembly. I was surprised to find elements for which TIR length was longer than MITE length. Considering that a MITE consists of two TIRs and some internal region, this seems quite strange. The following example is from your results:
_MITE_T_1|chr12|14935570|14935993|CC|430|F1 TSD_IN:no **MITE_LEN:423** **TIR_LEN:430** CANDIDATE_ID:MITE_CAND_446133 COMMON_TSD:aaa_
How would you explain a result like the one above where the MITE itself seems to be shorter than the TIRs it bears?
Thanks for your explanation!
Marius

**Comment by juancresc** [comment]
Hello Marius,

The problem in this case is the way in which the TIR lenght is reported by the program. If you take that MITE sequence, reverse complement it and align against the original, you'll see that you have an overall a good alignment

https://mafft.cbrc.jp/alignment/server/spool/_ho.190311232414059YOWy7XQ0RMupr4mnehIlglsfnormal.html

This means that you have a very long TIR to work with. Next, the algorithm starts searching for valid TSDs (~findir.py:114). The reported TIR length in the output corresponds to the original TIR alignment, sometimes can be larger than the final MITE. 

I'll evaluate making a re-calculation of the TIR lenght

**Comment by madelhorius** [comment]
I see, thanks for your explanation! Yes, it would be great to have re-calculated TIR length to work with.

**Comment by juancresc** [comment]
This is going to the backlog of the next release.
