### ISSUE TITLE
Vsearh clustering file not found error

### ISSUE THREAD

**Issue by Pushya-Krishna** [INTABiotechMJ/MITE-Tracker#6]
I am having some trouble running MITE Tracker properly. It seems to successfully identify MITE's but once it proceeds to the clustering steps it returns the error. I have tried re-installing Vsearch and I can locate all of the files specified in the traceback in my MITE-Tracker 
directory folder. Any suggestions? Thank you very much.

![Filenotfounderror](https://user-images.githubusercontent.com/52838810/61156530-d702e000-a4b0-11e9-8c75-866286839453.JPG)

**Comment by juancresc** [comment]
what is the output of:
`pwd`
`ls -lah vsearch-2.7.1/bin/`

**Comment by Pushya-Krishna** [comment]
This is what it looked like unfortunately.
![pwd ls lah vsearch](https://user-images.githubusercontent.com/52838810/61227822-49a6d200-a6e2-11e9-8da4-7195fd7d4b60.JPG)

**Comment by juancresc** [comment]
This is good, meaning that vsearch is not in the same directory as MITE Tracker is. Please make sure to follow this part in the same directory

```
wget https://github.com/torognes/vsearch/archive/v2.7.1.tar.gz
tar xzf v2.7.1.tar.gz
cd vsearch-2.7.1
#might need: sudo apt-get install autoconf
sh autogen.sh
./configure
make


```

**Comment by Pushya-Krishna** [comment]
When I try to run that script, the terminal window outputs a "bash: sh: command not found" error.
Is this something that I need to run in the usr/bin directory? Thanks for the help by the way, I greatly appreciate it.

**Comment by juancresc** [comment]
you can do everything in any directory. 
What about something like this?
```
chmod +x autogen.sh
./autogen.sh
```
also install autoconf as suggested

**Comment by Pushya-Krishna** [comment]
Hi sorry for the late response. Since cygwin was giving me trouble because it did not recognize sudo and apt-get commands, I am using the linux subsystem for windows (ubuntu). I re-entered your suggestions and this is the issue I am receiving. 
![configure error](https://user-images.githubusercontent.com/52838810/61397758-d2ab3e00-a887-11e9-9832-0b7adaba39f6.JPG)

**Comment by juancresc** [comment]
looks like a problem with vsearch installation itself. I'd recommend first try in a linux machine, if the problem persist post to https://github.com/torognes/vsearch
