### ISSUE TITLE
filter blastn output

### ISSUE THREAD

**Issue by bioteksampath** [INTABiotechMJ/MITE-Tracker#7]
Hi,
This tool seems very interesting, thanks for developing it.

I could follow until blastn of candidates MITEs with the genome fasta sequence. I have the blast_families_ata.csv file. But I am not clear how to filter the blast output to create gff.

'''
Let's run out notebook for filtering blast results, run till the end. This will explain at each step how filtering is done and what are the results.

jupyter lab

''''

Plz clarify 
Thanks in advance.
sam

**Comment by juancresc** [comment]
Yes, when opening Jupyer lab, open _filter_blast.ipynb_

**Comment by bioteksampath** [comment]
Thanks...
But I have a problem installing Jupiter lab. will get back to you if not works?

**Comment by juancresc** [comment]
what problem is it?
