### ISSUE TITLE
representative seq from valid families

### ISSUE THREAD

**Issue by LisaBlazek** [INTABiotechMJ/MITE-Tracker#8]
hallo!
i wanted to ask if there is a easy way to find out what families cluster together?
what i want to know is which other sequences the representative from families_nr.fasta belongs to.

also im curious whats the difference between the all.fasta and families.txt?
and are the all.fasta all full-length MITEs?

i really like the program and hopefully you can help me :)

**Comment by juancresc** [comment]
hey, 

the families.fasta file will give you that information
